#!/usr/bin/env bash

# Organizes images, as output from a Matlab image scrambling
# script, into folders by original image. Supports up to 99
# images (can be easily updated by adding a condition to line
# 23) as-is. Runs in bash >= 3.0.
# 
# Copyright (c) 2016 Austin Marcus.
# All rights reserved.
#
# This file is part of the ShellScripts repository, and is
# made available under the terms of the GNU Public License
# (see LICENSE file).

COUNTER=1
MAX=$1+1

while [ $COUNTER -lt $MAX ];
do
	mkdir Im_$COUNTER
	for file in *.jpg;
	do
		NUMSTR=${file:3:2}
		if [[ $NUMSTR = 0${COUNTER} ]] || [[ $NUMSTR = ${COUNTER} ]]; then
			mv $file Im_$COUNTER
		fi
	done
	let COUNTER=COUNTER+1
done
